/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.calculadora;

import java.awt.Color;

/**
 *
 * @author Programacao
 */
public class Calculadora extends javax.swing.JFrame {

    private String numero1;
    private String numero2;
    private String resultado;
    
    CalculadoraFuncionalidad calculadora = new CalculadoraFuncionalidad();
    

    
    
        private void actualizarPantalla(String texto) {
        String currentText = txtCalculadora.getText();

        if (texto.equals("=")) {
            // Evaluar la operación esto es solo un ejemplo, puedes implementar el cálculo aquí
            try {
                // Usamos la clase `ScriptEngine` para evaluar expresiones matemáticas (esto es solo un ejemplo)
                javax.script.ScriptEngineManager mgr = new javax.script.ScriptEngineManager();
                javax.script.ScriptEngine engine = mgr.getEngineByName("JavaScript");
                Object result = engine.eval(currentText);
                txtCalculadora.setText(result.toString());
            } catch (Exception ex) {
                txtCalculadora.setText("Error");
            }
        } else {
            txtCalculadora.setText(currentText + texto);  // Agregar el texto del botón presionado
        }
    }
    
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt4 = new javax.swing.JLabel();
        txtClear = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txtResta = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txtDecimal = new javax.swing.JLabel();
        txtDiv = new javax.swing.JLabel();
        txtMult = new javax.swing.JLabel();
        txtSuma = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txt6 = new javax.swing.JLabel();
        txt7 = new javax.swing.JLabel();
        txt8 = new javax.swing.JLabel();
        txt9 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JLabel();
        txtPositivo = new javax.swing.JLabel();
        txtCalculadora = new javax.swing.JTextField();
        txt0 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        txt4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txt4.setText("4");
        txt4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt4MouseReleased(evt);
            }
        });

        txtClear.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        txtClear.setForeground(new java.awt.Color(0, 0, 0));
        txtClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris claro.png.png"))); // NOI18N
        txtClear.setText("AC");
        txtClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtClearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtClearMouseReleased(evt);
            }
        });

        txt3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txt3.setText("3");
        txt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt3MouseReleased(evt);
            }
        });

        txtResta.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txtResta.setForeground(new java.awt.Color(255, 255, 255));
        txtResta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/naranja.png"))); // NOI18N
        txtResta.setText("-");
        txtResta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtResta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRestaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtRestaMouseReleased(evt);
            }
        });

        txt2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txt2.setText("2");
        txt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt2MouseReleased(evt);
            }
        });

        txtDecimal.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txtDecimal.setForeground(new java.awt.Color(255, 255, 255));
        txtDecimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDecimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txtDecimal.setText(",");
        txtDecimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDecimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtDecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDecimalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtDecimalMouseReleased(evt);
            }
        });

        txtDiv.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txtDiv.setForeground(new java.awt.Color(255, 255, 255));
        txtDiv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/naranja.png"))); // NOI18N
        txtDiv.setText("÷");
        txtDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDivMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtDivMouseReleased(evt);
            }
        });

        txtMult.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txtMult.setForeground(new java.awt.Color(255, 255, 255));
        txtMult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/naranja.png"))); // NOI18N
        txtMult.setText("x");
        txtMult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtMult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMultMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtMultMouseReleased(evt);
            }
        });

        txtSuma.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txtSuma.setForeground(new java.awt.Color(255, 255, 255));
        txtSuma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/naranja.png"))); // NOI18N
        txtSuma.setText("+");
        txtSuma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSumaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtSumaMouseReleased(evt);
            }
        });

        txtResultado.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/naranja.png"))); // NOI18N
        txtResultado.setText("=");
        txtResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtResultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtResultadoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtResultadoMouseReleased(evt);
            }
        });

        txt1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txt1.setText("1");
        txt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt1MouseReleased(evt);
            }
        });

        txt6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txt6.setForeground(new java.awt.Color(255, 255, 255));
        txt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txt6.setText("6");
        txt6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt6MouseReleased(evt);
            }
        });

        txt7.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txt7.setForeground(new java.awt.Color(255, 255, 255));
        txt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txt7.setText("7");
        txt7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt7MouseReleased(evt);
            }
        });

        txt8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txt8.setForeground(new java.awt.Color(255, 255, 255));
        txt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txt8.setText("8");
        txt8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt8MouseReleased(evt);
            }
        });

        txt9.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txt9.setForeground(new java.awt.Color(255, 255, 255));
        txt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txt9.setText("9");
        txt9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt9MouseReleased(evt);
            }
        });

        txt5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txt5.setForeground(new java.awt.Color(255, 255, 255));
        txt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris oscuro.png"))); // NOI18N
        txt5.setText("5");
        txt5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt5MouseReleased(evt);
            }
        });

        txtPorcentaje.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        txtPorcentaje.setForeground(new java.awt.Color(0, 0, 0));
        txtPorcentaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris claro.png.png"))); // NOI18N
        txtPorcentaje.setText("%");
        txtPorcentaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtPorcentaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPorcentajeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPorcentajeMouseReleased(evt);
            }
        });

        txtPositivo.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        txtPositivo.setForeground(new java.awt.Color(0, 0, 0));
        txtPositivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gris claro.png.png"))); // NOI18N
        txtPositivo.setText(" +\\- ");
        txtPositivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtPositivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPositivoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPositivoMouseReleased(evt);
            }
        });

        txtCalculadora.setEditable(false);
        txtCalculadora.setBackground(new java.awt.Color(0, 0, 0));
        txtCalculadora.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        txtCalculadora.setForeground(new java.awt.Color(255, 255, 255));
        txtCalculadora.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCalculadora.setText("123456789");
        txtCalculadora.setBorder(null);
        txtCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalculadoraActionPerformed(evt);
            }
        });

        txt0.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt0.setForeground(new java.awt.Color(255, 255, 255));
        txt0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zero.png"))); // NOI18N
        txt0.setText("0");
        txt0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt0MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtClear)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPositivo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt8)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMult))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPorcentaje)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDiv))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt1)
                                    .addComponent(txt4))
                                .addGap(18, 18, 18)
                                .addComponent(txt5)
                                .addGap(18, 18, 18)
                                .addComponent(txt6)
                                .addGap(18, 18, 18)
                                .addComponent(txtResta))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(txt2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txt3)
                                .addGap(18, 18, 18)
                                .addComponent(txtSuma))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDecimal)
                                .addGap(18, 18, 18)
                                .addComponent(txtResultado)))))
                .addGap(325, 325, 325))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(txtCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPorcentaje)
                    .addComponent(txtPositivo)
                    .addComponent(txtClear)
                    .addComponent(txtDiv))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt9)
                    .addComponent(txt8)
                    .addComponent(txt7)
                    .addComponent(txtMult))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtResta)
                                .addComponent(txt6)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2)
                            .addComponent(txt1)
                            .addComponent(txt3)
                            .addComponent(txtSuma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDecimal)
                            .addComponent(txtResultado))))
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // txtCalculadora.setText("0");
    }//GEN-LAST:event_formWindowOpened

    private void txtSumaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSumaMouseReleased
        txtSuma.setForeground(Color.white);
    }//GEN-LAST:event_txtSumaMouseReleased

    private void txtSumaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSumaMousePressed
        txtSuma.setForeground(Color.black);
        calculadora.setOperacion("+");
        numero1 = txtCalculadora.getText();
        double doubleNumero1;
        doubleNumero1 = Double.parseDouble(numero1);
        calculadora.setNumero1(doubleNumero1);
        txtCalculadora.setText("");
        System.out.println("Operador establecido: " + calculadora.getOperacion());
        System.out.println("numero1: " + calculadora.getNumero1());

        /*numero1 = txtCalculadora.getText();
        calculadora.setNumero1(Double.parseDouble(numero1));
        calculadora.setOperacion("+");
        txtCalculadora.setText("");
        System.out.println(numero1);*/
    }//GEN-LAST:event_txtSumaMousePressed

    private void txt7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt7MouseReleased
        txt7.setForeground(Color.white);
    }//GEN-LAST:event_txt7MouseReleased

    private void txt7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt7MousePressed
        txt7.setForeground(Color.black);
        actualizarPantalla(txt7.getText());
    }//GEN-LAST:event_txt7MousePressed

    private void txt0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt0MouseReleased
        txt0.setForeground(Color.white);
    }//GEN-LAST:event_txt0MouseReleased

    private void txt0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt0MousePressed
        txt0.setForeground(Color.black);
        actualizarPantalla(txt0.getText());
    }//GEN-LAST:event_txt0MousePressed

    private void txt9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt9MouseReleased
        txt9.setForeground(Color.white);
    }//GEN-LAST:event_txt9MouseReleased

    private void txt9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt9MousePressed
        txt9.setForeground(Color.black);
        actualizarPantalla(txt9.getText());
    }//GEN-LAST:event_txt9MousePressed

    private void txtDivMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDivMouseReleased
        txtDiv.setForeground(Color.white);
    }//GEN-LAST:event_txtDivMouseReleased

    private void txtDivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDivMousePressed
        txtDiv.setForeground(Color.black);
        calculadora.setOperacion("/");
        numero1 = txtCalculadora.getText();
        double doubleNumero1;
        doubleNumero1 = Double.parseDouble(numero1);
        calculadora.setNumero1(doubleNumero1);
        txtCalculadora.setText("");
        System.out.println("Operador establecido: " + calculadora.getOperacion());
        System.out.println("numero1: " + calculadora.getNumero1());
    }//GEN-LAST:event_txtDivMousePressed

    private void txt4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt4MouseReleased
        txt4.setForeground(Color.white);
    }//GEN-LAST:event_txt4MouseReleased

    private void txt4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt4MousePressed
        txt4.setForeground(Color.black);
        actualizarPantalla(txt4.getText());
    }//GEN-LAST:event_txt4MousePressed

    private void txt2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt2MouseReleased
        txt2.setForeground(Color.white);
    }//GEN-LAST:event_txt2MouseReleased

    private void txt2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt2MousePressed
        txt2.setForeground(Color.black);
        actualizarPantalla(txt2.getText());
    }//GEN-LAST:event_txt2MousePressed

    private void txtRestaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRestaMouseReleased
        txtResta.setForeground(Color.white);
    }//GEN-LAST:event_txtRestaMouseReleased

    private void txtRestaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRestaMousePressed
        txtResta.setForeground(Color.black);
        //actualizarPantalla(txtResta.getText());
        calculadora.setOperacion("-");
        numero1 = txtCalculadora.getText();
        double doubleNumero1;
        doubleNumero1 = Double.parseDouble(numero1);
        calculadora.setNumero1(doubleNumero1);
        txtCalculadora.setText("");
        System.out.println("Operador establecido: " + calculadora.getOperacion());
        System.out.println("numero1: " + calculadora.getNumero1());

    }//GEN-LAST:event_txtRestaMousePressed

    private void txtPorcentajeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPorcentajeMouseReleased
        txtPorcentaje.setForeground(Color.black);
    }//GEN-LAST:event_txtPorcentajeMouseReleased

    private void txtPorcentajeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPorcentajeMousePressed
        txtPorcentaje.setForeground(Color.white);
        actualizarPantalla(txtPorcentaje.getText());
    }//GEN-LAST:event_txtPorcentajeMousePressed

    private void txtResultadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResultadoMouseReleased
        txtResultado.setForeground(Color.white);
    }//GEN-LAST:event_txtResultadoMouseReleased

    private void txtResultadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResultadoMousePressed
        txtResultado.setForeground(Color.black);
        numero2 = txtCalculadora.getText();
        double doubleNumero2;
        doubleNumero2 = Double.parseDouble(numero2);
        calculadora.setNumero2(doubleNumero2);
        calculadora.calcular();
        txtCalculadora.setText(String.valueOf(calculadora.getResultado()));

        System.out.println("numero1 " + calculadora.getNumero1() + "numero 2 " +calculadora.getNumero2() + "resultado " +calculadora.getResultado());
        /*calculadora.setNumero2(Double.parseDouble(numero2));
        System.out.println("numero1 " + numero1 + "numero 2 " +numero2 + "resultado " +resultado);
        System.out.println(numero1+numero2);
        resultado = numero1 + numero2;
        calculadora.calcular();
        txtCalculadora.setText(String.valueOf(calculadora.getResultado()));
        System.out.println("numero1 " + numero1 + "numero 2 " +numero2 + "resultado " +calculadora.getResultado());
        calculadora.limpiar();*/

    }//GEN-LAST:event_txtResultadoMousePressed

    private void txtPositivoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPositivoMouseReleased
        txtPositivo.setForeground(Color.black);
    }//GEN-LAST:event_txtPositivoMouseReleased

    private void txtPositivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPositivoMousePressed
        txtPositivo.setForeground(Color.white);

    }//GEN-LAST:event_txtPositivoMousePressed

    private void txt1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseReleased
        txt1.setForeground(Color.white);
    }//GEN-LAST:event_txt1MouseReleased

    private void txt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MousePressed
        txt1.setForeground(Color.black);
        actualizarPantalla(txt1.getText());
    }//GEN-LAST:event_txt1MousePressed

    private void txt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseExited

    }//GEN-LAST:event_txt1MouseExited

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
        //txt1.setForeground(Color.black);
    }//GEN-LAST:event_txt1MouseClicked

    private void txt5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt5MouseReleased
        txt5.setForeground(Color.white);
    }//GEN-LAST:event_txt5MouseReleased

    private void txt5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt5MousePressed
        txt5.setForeground(Color.black);
        actualizarPantalla(txt5.getText());
    }//GEN-LAST:event_txt5MousePressed

    private void txt8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt8MouseReleased
        txt8.setForeground(Color.white);
    }//GEN-LAST:event_txt8MouseReleased

    private void txt8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt8MousePressed
        txt8.setForeground(Color.black);
        actualizarPantalla(txt8.getText());
    }//GEN-LAST:event_txt8MousePressed

    private void txt6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt6MouseReleased
        txt6.setForeground(Color.white);
    }//GEN-LAST:event_txt6MouseReleased

    private void txt6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt6MousePressed
        txt6.setForeground(Color.black);
        actualizarPantalla(txt6.getText());
    }//GEN-LAST:event_txt6MousePressed

    private void txt3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt3MouseReleased
        txt3.setForeground(Color.white);
    }//GEN-LAST:event_txt3MouseReleased

    private void txt3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt3MousePressed
        txt3.setForeground(Color.black);
        actualizarPantalla(txt3.getText());
    }//GEN-LAST:event_txt3MousePressed

    private void txtMultMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMultMouseReleased
        txtMult.setForeground(Color.white);
    }//GEN-LAST:event_txtMultMouseReleased

    private void txtMultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMultMousePressed
        txtMult.setForeground(Color.black);
        calculadora.setOperacion("*");
        numero1 = txtCalculadora.getText();
        double doubleNumero1;
        doubleNumero1 = Double.parseDouble(numero1);
        calculadora.setNumero1(doubleNumero1);
        txtCalculadora.setText("");
        System.out.println("Operador establecido: " + calculadora.getOperacion());
        System.out.println("numero1: " + calculadora.getNumero1());
    }//GEN-LAST:event_txtMultMousePressed

    private void txtDecimalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDecimalMouseReleased
        txtDecimal.setForeground(Color.white);
    }//GEN-LAST:event_txtDecimalMouseReleased

    private void txtDecimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDecimalMousePressed
        txtDecimal.setForeground(Color.black);
        actualizarPantalla(txtDecimal.getText());
    }//GEN-LAST:event_txtDecimalMousePressed

    private void txtClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClearMouseReleased
        txtClear.setForeground(Color.black);
    }//GEN-LAST:event_txtClearMouseReleased

    private void txtClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClearMousePressed
        txtClear.setForeground(Color.white);
        calculadora.limpiar();
        txtCalculadora.setText("");

    }//GEN-LAST:event_txtClearMousePressed

    private void txtCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalculadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculadora().setVisible(true);
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt0;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txt7;
    private javax.swing.JLabel txt8;
    private javax.swing.JLabel txt9;
    private javax.swing.JTextField txtCalculadora;
    private javax.swing.JLabel txtClear;
    private javax.swing.JLabel txtDecimal;
    private javax.swing.JLabel txtDiv;
    private javax.swing.JLabel txtMult;
    private javax.swing.JLabel txtPorcentaje;
    private javax.swing.JLabel txtPositivo;
    private javax.swing.JLabel txtResta;
    private javax.swing.JLabel txtResultado;
    private javax.swing.JLabel txtSuma;
    // End of variables declaration//GEN-END:variables
}
